"""Versioned structured artifacts exchanged between workflow stages."""

from contracts.artifacts import (
    AnalysisReport,
    Artifact,
    CheckResult,
    CheckStatus,
    CriterionAssessment,
    CriterionStatus,
    Defect,
    ImplementationResult,
    ImplementationStatus,
    QADecision,
    QAReport,
    ReviewDecision,
    ReviewFinding,
    ReviewReport,
    Severity,
    SpecificationDecision,
    TaskRequest,
    TaskSpecification,
    ValidationDecision,
    ValidationResult,
)
from contracts.evidence import ArtifactReference, Evidence, EvidenceKind

__all__ = [
    "AnalysisReport",
    "Artifact",
    "ArtifactReference",
    "CheckResult",
    "CheckStatus",
    "CriterionAssessment",
    "CriterionStatus",
    "Defect",
    "Evidence",
    "EvidenceKind",
    "ImplementationResult",
    "ImplementationStatus",
    "QADecision",
    "QAReport",
    "ReviewDecision",
    "ReviewFinding",
    "ReviewReport",
    "Severity",
    "SpecificationDecision",
    "TaskRequest",
    "TaskSpecification",
    "ValidationDecision",
    "ValidationResult",
]
